#!/bin/sh

 
function usage(){
	printf "Script options :\n"
	printf "\t-H	: specify new hostname.\n"
        printf "\t-u    : specify new username.\n"
	printf "\t-p 	: specify new SSH port.\n"
	printf "\t-h    : display this.\n"
}


#while true ; do
while getopts ":hu:p:H:" option; do
    case "$option" in
	h)     
		usage; 
		exit 0
		;;
        u)   
		username=$OPTARG
		echo $username
		;;
        p)   
                ssh_port=$OPTARG
                echo $ssh_port
                ;;
        H)   
                hostname=$OPTARG
                echo $hostname
                ;;
        --)              
		break;; # end of options
    esac
done

# Set groups for new user
NEW_USER_GROUPS="adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi"

# create new user
if [ -z "$username" ]; then
	printf "Type in new username, followed by [ENTER]:"
	read username
fi

printf "Create user $username..."
sudo useradd $username -G $NEW_USER_GROUPS -m
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

sudo passwd nbonniot

# Copy all pi user home files to set it to new user
printf "Copy all pi user home files to $username home folder...\n"
sudo cp -R ~/* /home/$username/
sudo cp -R ~/.* /home/$username/
sudo chown -R $username:$username /home/$username
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

# Set boot behavior to console
printf "Set boot behavior to console, no login...\n"
sudo raspi-config nonint do_boot_behaviour_new B1
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"


# Wait for network to init
printf "Set system to wait for network to init...\n"
sudo raspi-config nonint do_wait_for_network Slow
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"


# Extend root FS
printf "Expand root FS to fill all memory card...\n"
sudo raspi-config nonint do_expand_rootfs
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

printf "Activate SSH server...\n"
sudo raspi-config nonint do_ssh 0
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

printf "Change SSH port and allow only $username connections...\n"
if [ -z "$port" ]; then
	printf "Type in new SSH port [6061]:"
        read ssh_port
fi
port=${ssh_port:=6061}

sudo sed -i "s/Port 22/Port $ssh_port\nAllowUsers $username/g" /etc/ssh/sshd_config
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

printf "Activate I2C on startup...\n"
sudo raspi-config nonint do_i2c 0
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

printf "Activate SPI on startup...\n"
sudo raspi-config nonint do_spi 0
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

# Rename hostname
if [ -z "$hostname" ]; then
	printf "Type in new hostname, followed by [ENTER]:"
	read hostname
fi

sudo raspi-config nonint do_change_hostname $hostname
printf "\e[1m\e[32mDONE\e[39m\e[21m\n"

printf "REBOOT\n"
sudo reboot
